version: '3.8'

services:
  mosquitto:
    image: ahsankoushik/mosq-rest-auth:v.1
    container_name: mosquser
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/etc/mosquitto/mosquitto.conf
      # - ./mosquitto/auth-plugin:/mosquitto/auth-plugin
    restart: always


