
# MQTTS (MQTT over TLS)
listener 8883
protocol mqtt
allow_anonymous false
cafile /mosquitto/certs/fullchain.pem
certfile /mosquitto/certs/fullchain.pem
keyfile /mosquitto/certs/privkey.pem

# WSS (WebSockets over TLS)
listener 9001
protocol websockets
allow_anonymous false
cafile /mosquitto/certs/fullchain.pem
certfile /mosquitto/certs/fullchain.pem
keyfile /mosquitto/certs/privkey.pem

# Auth Plugin
plugin /auth-plugin/auth-plug.so
plugin_opt_backends http

plugin_opt_http_ip 172.17.0.1
plugin_opt_http_port 6999
plugin_opt_http_getuser_uri /mosq/auth
plugin_opt_http_superuser_uri /mosq/superuser
plugin_opt_http_aclcheck_uri /mosq/acl

# Logging
log_type all
log_dest stdout

